FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install -g npm@12
RUN npm ci

COPY . .
RUN npm run build

# ---- runner ----
FROM node:24-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

# Next.js standalone output
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
